/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./types/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#0d1c32",
        "tertiary-fixed-dim": "#c9c6c1",
        "outline-variant": "#c5c6cd",
        "error-container": "#ffdad6",
        "tertiary-container": "#1c1c18",
        "surface": "#fcf9f8",
        "primary": "#000000",
        "surface-container-high": "#eae7e7",
        "on-secondary-container": "#745c00",
        "primary-fixed": "#d6e3ff",
        "background": "#fcf9f8",
        "error": "#ba1a1a",
        "tertiary-fixed": "#e5e2dc",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#e9c349",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1b1c1c",
        "secondary-fixed": "#ffe088",
        "on-surface": "#1b1c1c",
        "on-primary-fixed-variant": "#39475f",
        "on-secondary-fixed-variant": "#574500",
        "surface-container": "#f0eded",
        "primary-container": "#0d1c32",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-secondary-fixed": "#241a00",
        "on-surface-variant": "#44474d",
        "on-tertiary-container": "#85847f",
        "tertiary": "#000000",
        "surface-container-highest": "#e4e2e1",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#75777e",
        "surface-bright": "#fcf9f8",
        "secondary-container": "#fed65b",
        "surface-dim": "#dcd9d9",
        "on-primary-container": "#76849f",
        "surface-tint": "#515f78",
        "inverse-primary": "#b9c7e4",
        "surface-variant": "#e4e2e1",
        "on-tertiary-fixed-variant": "#474743",
        "on-tertiary-fixed": "#1c1c18",
        "primary-fixed-dim": "#b9c7e4",
        "secondary": "#735c00",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "32px",
        unit: "8px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "section-gap": "120px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        body: ["var(--font-body)", "Montserrat"],
        display: ["var(--font-display)", "Playfair Display"],
        "body-md": ["Montserrat"],
        "display-lg-mobile": ["Playfair Display"],
        "headline-sm": ["Playfair Display"],
        "label-caps": ["Montserrat"],
        "headline-md": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "body-lg": ["Montserrat"],
        button: ["Montserrat"],
      },
      fontSize: {
        button: ["14px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
